"""Recon-tier tool wrappers — transport-tier fact-emitters (plan §6, §9, §13; v1.8).

Asserts the Big-Task-1 DoD, all network-free (recorded fixtures, no real binaries):

  1. Each wrapper parses its tool's recorded output into the correct transport-tier
     graph facts — ``Host``/``Service`` nodes, ``runs_service``/``resolves_to``
     edges, ``Endpoint`` nodes for discovered paths, tech/version attributes.
  2. Scope allowlist is enforced *before any spawn*: an out-of-scope target is
     refused and audited, and no process is launched (proven — ``ingest`` never
     spawns, and the live ``run`` path is asserted to refuse pre-spawn).
  3. A missing binary is a clean, audited skip — never a crash.
  4. Command safety: the built argv is an array, ``shell=False``, and the target is
     a distinct arg element (never interpolated into a shell string).
  5. **The recon-tier invariant**: after every wrapper runs, the graph holds ZERO
     findings, ZERO candidates, and ZERO ``can_call`` edges. Recon emits facts only.
  6. The live path is env-gated (``REACHAGENT_RECON_LIVE``) and skipped by default.

Fixtures live under ``tests/phase3/fixtures/recon/`` — captured tool output, read
from disk, never regenerated by invoking a real tool.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from reachagent.execution.scope import ScopeGuard
from reachagent.graph.store import ReachabilityGraph, host_id
from reachagent.recon.tools import (
    AmassRunner,
    GobusterRunner,
    NmapRunner,
    ReconOutcome,
    ReconToolRunner,
    SubfinderRunner,
    WhatWebRunner,
)
from reachagent.recon.tools.base import _scope_url

_FIXTURES = Path(__file__).parent / "fixtures" / "recon"
_TARGET = "target.test"


def _fixture(name: str) -> str:
    return (_FIXTURES / name).read_text(encoding="utf-8")


def _scope() -> ScopeGuard:
    return ScopeGuard.from_hosts(["target.test"])


def _graph_and_scope() -> tuple[ReachabilityGraph, ScopeGuard]:
    return ReachabilityGraph(), _scope()


# ---------------------------------------------------------------------------
# 1. Per-tool fixture parse → correct transport-tier facts
# ---------------------------------------------------------------------------


def test_nmap_emits_host_and_open_services() -> None:
    graph, scope = _graph_and_scope()
    runner = NmapRunner(graph=graph, scope=scope)
    result = runner.ingest(_TARGET, _fixture("nmap-target.xml"))

    assert result.outcome is ReconOutcome.INGESTED
    # One host, keyed by its IPv4 address, tech from osmatch.
    hosts = graph.hosts()
    assert len(hosts) == 1
    host_node, host = hosts[0]
    assert host_node == host_id("93.184.216.34")
    assert host.hostname == "target.test"
    assert host.source == "nmap"
    assert host.technology == "Linux 5.X"
    # Only the three OPEN ports become services — the closed 3306 does not.
    services = graph.services()
    assert len(services) == 3
    ports = {s.port for _, s in services}
    assert ports == {22, 80, 443}
    # runs_service edges connect host → each service.
    assert len(graph.runs_service_edges()) == 3
    # A service carries its version banner (a fact), no status.
    http = next(s for _, s in services if s.port == 80)
    assert http.service_name == "http"
    assert http.detected_version == "1.24.0"
    assert "nginx" in (http.banner or "")


def test_amass_emits_one_host_per_subdomain_deduped() -> None:
    graph, scope = _graph_and_scope()
    runner = AmassRunner(graph=graph, scope=scope)
    result = runner.ingest(_TARGET, _fixture("amass-target.txt"))

    assert result.outcome is ReconOutcome.INGESTED
    hostnames = {h.hostname for _, h in graph.hosts()}
    # Four distinct subdomains — the duplicate www line is deduped, comment skipped.
    assert hostnames == {
        "www.target.test",
        "api.target.test",
        "mail.target.test",
        "admin.target.test",
    }
    assert all(h.source == "amass" for _, h in graph.hosts())
    # A subdomain is a Host, not a Subdomain node — no service, no path.
    assert graph.services() == []


def test_subfinder_emits_one_host_per_subdomain() -> None:
    graph, scope = _graph_and_scope()
    runner = SubfinderRunner(graph=graph, scope=scope)
    result = runner.ingest(_TARGET, _fixture("subfinder-target.txt"))

    assert result.outcome is ReconOutcome.INGESTED
    hostnames = {h.hostname for _, h in graph.hosts()}
    assert hostnames == {
        "api.target.test",
        "dev.target.test",
        "staging.target.test",
        "vpn.target.test",
    }
    assert all(h.source == "subfinder" for _, h in graph.hosts())


def test_gobuster_emits_endpoints_with_resolves_to_edges() -> None:
    graph, scope = _graph_and_scope()
    runner = GobusterRunner(graph=graph, scope=scope)
    result = runner.ingest(_TARGET, _fixture("gobuster-target.txt"))

    assert result.outcome is ReconOutcome.INGESTED
    # Discovered paths are ordinary Endpoint nodes (no new type).
    paths = {ep.path for _, ep in graph.endpoints()}
    assert paths == {"/admin", "/login", "/api", "/.htaccess", "/uploads"}
    # Each attaches to the target Host via a resolves_to edge.
    edges = graph.resolves_to_edges()
    assert len(edges) == 5
    assert all(src == host_id("target.test") for src, _ in edges)
    # Every discovered endpoint is a plain GET probe — recon assigns no can_call.
    assert all(ep.method == "GET" for _, ep in graph.endpoints())


def test_whatweb_emits_host_tech_attributes_no_technology_node() -> None:
    graph, scope = _graph_and_scope()
    runner = WhatWebRunner(graph=graph, scope=scope)
    result = runner.ingest(_TARGET, _fixture("whatweb-target.json"))

    assert result.outcome is ReconOutcome.INGESTED
    # The root record → the Host carries technology/version as ATTRIBUTES.
    (_, host) = next((n, h) for n, h in graph.hosts() if h.address == "target.test")
    assert host.source == "whatweb"
    assert "WordPress" in (host.technology or "")
    assert "PHP" in (host.technology or "")
    assert host.detected_version == "6.4.2"
    # Transport noise plugins are excluded from the technology attribute.
    assert "HTTPServer" not in (host.technology or "")
    assert "Cookies" not in (host.technology or "")
    # The /blog record → a per-endpoint fingerprint reused on the Endpoint, with a
    # resolves_to edge. No Technology node exists — only host/service/endpoint kinds.
    blog = next(ep for _, ep in graph.endpoints() if ep.path == "/blog")
    assert "WordPress" in (blog.technology or "")
    assert graph.resolves_to_edges()
    kinds = {attrs["kind"] for _, attrs in graph._g.nodes(data=True)}  # noqa: SLF001
    assert kinds <= {"host", "service", "endpoint"}
    assert "technology" not in kinds  # no per-class Technology node (§6)


# ---------------------------------------------------------------------------
# 2. Scope enforced before any spawn (refused + audited, nothing launched)
# ---------------------------------------------------------------------------

_ALL_RUNNERS = [NmapRunner, AmassRunner, SubfinderRunner, GobusterRunner, WhatWebRunner]


@pytest.mark.parametrize("runner_cls", _ALL_RUNNERS)
def test_out_of_scope_target_is_refused_and_audited(runner_cls: type[ReconToolRunner]) -> None:
    graph = ReachabilityGraph()
    scope = ScopeGuard.from_hosts(["in-scope.test"])  # target.test is NOT allowed
    runner = runner_cls(graph=graph, scope=scope)

    result = runner.ingest("evil.test", "irrelevant output")

    assert result.outcome is ReconOutcome.REFUSED_OUT_OF_SCOPE
    # Nothing was written to the graph for an out-of-scope target.
    assert graph.node_count() == 0
    # And the refusal is audited, same discipline as the firer.
    assert runner.audit.entries[-1].outcome == ReconOutcome.REFUSED_OUT_OF_SCOPE


def test_live_run_refuses_out_of_scope_before_spawning(monkeypatch: pytest.MonkeyPatch) -> None:
    # Even on the live path, scope is enforced BEFORE any spawn. We make a spawn
    # explode if reached; an out-of-scope target must never reach it.
    import reachagent.recon.tools.base as base

    def _boom(*_a: object, **_k: object) -> object:
        raise AssertionError("subprocess.run must not be reached for an out-of-scope target")

    monkeypatch.setattr(base.subprocess, "run", _boom)
    graph = ReachabilityGraph()
    scope = ScopeGuard.from_hosts(["in-scope.test"])
    runner = NmapRunner(graph=graph, scope=scope)

    result = runner.run("evil.test", environ={base.RECON_ENV_LIVE: "1"})

    assert result.outcome is ReconOutcome.REFUSED_OUT_OF_SCOPE
    assert graph.node_count() == 0


# ---------------------------------------------------------------------------
# 3. Missing binary → clean, audited skip (never a crash)
# ---------------------------------------------------------------------------


def test_missing_binary_skips_cleanly(monkeypatch: pytest.MonkeyPatch) -> None:
    import reachagent.recon.tools.base as base

    # Binary absent from PATH.
    monkeypatch.setattr(base.shutil, "which", lambda _b: None)
    # Guard: a spawn must not be attempted when the binary is missing.
    monkeypatch.setattr(
        base.subprocess,
        "run",
        lambda *_a, **_k: (_ for _ in ()).throw(
            AssertionError("must not spawn when binary is missing")
        ),
    )
    graph = ReachabilityGraph()
    runner = NmapRunner(graph=graph, scope=_scope())

    result = runner.run(_TARGET, environ={base.RECON_ENV_LIVE: "1"})

    assert result.outcome is ReconOutcome.SKIPPED_MISSING_BINARY
    assert graph.node_count() == 0
    assert runner.audit.entries[-1].outcome == ReconOutcome.SKIPPED_MISSING_BINARY


# ---------------------------------------------------------------------------
# 4. Command safety — argument array, shell=False, target as a distinct element
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("runner_cls", _ALL_RUNNERS)
def test_command_is_an_array_with_target_as_a_distinct_element(
    runner_cls: type[ReconToolRunner],
) -> None:
    runner = runner_cls(graph=ReachabilityGraph(), scope=_scope())
    argv = runner.command(_TARGET)
    # An argv LIST, not a shell string.
    assert isinstance(argv, list)
    assert all(isinstance(arg, str) for arg in argv)
    # The target is a whole element, never concatenated into another arg.
    assert _TARGET in argv
    # No element smuggles a shell metacharacter around the target.
    assert not any(";" in a or "&&" in a or "|" in a for a in argv)


def test_hostile_target_stays_a_single_arg_element() -> None:
    # A target carrying shell metacharacters must remain ONE argv element — with
    # shell=False that is inert, never a shell break-out.
    hostile = "target.test; rm -rf /"
    argv = NmapRunner(graph=ReachabilityGraph(), scope=_scope()).command(hostile)
    assert hostile in argv  # the whole hostile string is one element
    # It never gets split/joined into a shell string.
    assert argv.count(hostile) == 1


def test_live_spawn_uses_shell_false_and_array(monkeypatch: pytest.MonkeyPatch) -> None:
    # Capture the exact subprocess.run call the live path makes.
    import reachagent.recon.tools.base as base

    captured: dict[str, object] = {}

    class _Completed:
        stdout = ""

    def _fake_run(argv: object, **kwargs: object) -> _Completed:
        captured["argv"] = argv
        captured["kwargs"] = kwargs
        return _Completed()

    monkeypatch.setattr(base.shutil, "which", lambda _b: "/usr/bin/nmap")
    monkeypatch.setattr(base.subprocess, "run", _fake_run)
    runner = NmapRunner(graph=ReachabilityGraph(), scope=_scope())

    runner.run(_TARGET, environ={base.RECON_ENV_LIVE: "1"})

    assert isinstance(captured["argv"], list)  # array, not a string
    assert captured["kwargs"]["shell"] is False  # never shell=True
    assert _TARGET in captured["argv"]  # target is an element


def test_live_run_result_carries_the_real_command_and_output_preview(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """GUI live-feed visibility: a live run's result must carry the exact argv
    subprocess.run was handed, plus a short slice of real stdout — not just an
    outcome enum with no evidence of what actually ran."""
    import reachagent.recon.tools.base as base

    class _Completed:
        stdout = (
            "/admin                (Status: 200) [Size: 1234]\n"
            "/login                (Status: 301)\n"
        )

    def _fake_run(argv: object, **_kwargs: object) -> _Completed:
        return _Completed()

    monkeypatch.setattr(base.shutil, "which", lambda _b: "/usr/bin/gobuster")
    monkeypatch.setattr(base.subprocess, "run", _fake_run)
    runner = GobusterRunner(graph=ReachabilityGraph(), scope=_scope())

    result = runner.run(_TARGET, environ={base.RECON_ENV_LIVE: "1"})

    assert result.outcome is ReconOutcome.INGESTED
    assert result.command == tuple(runner.command(_TARGET))
    assert _TARGET in result.command
    assert "/admin" in result.output_preview
    assert result.output_preview  # non-empty for real output


def test_ingest_result_carries_an_output_preview() -> None:
    runner = GobusterRunner(graph=ReachabilityGraph(), scope=_scope())
    result = runner.ingest(_TARGET, "/admin                (Status: 200) [Size: 1234]\n")
    assert "/admin" in result.output_preview


def test_output_preview_still_present_on_a_parse_error() -> None:
    """A parse failure is exactly when a human most wants to see the raw output."""
    runner = NmapRunner(graph=ReachabilityGraph(), scope=_scope())
    result = runner.ingest(_TARGET, "not valid nmap XML at all")
    assert result.outcome is ReconOutcome.ERRORED
    assert "not valid nmap XML" in result.output_preview


def test_output_preview_is_bounded_for_a_huge_output() -> None:
    runner = GobusterRunner(graph=ReachabilityGraph(), scope=_scope())
    huge = "\n".join(f"/path{i}          (Status: 200)" for i in range(5000))
    result = runner.ingest(_TARGET, huge)
    assert len(result.output_preview) < len(huge)
    assert result.output_preview.endswith("…")


# ---------------------------------------------------------------------------
# 5. THE recon-tier invariant — zero findings / candidates / can_call
# ---------------------------------------------------------------------------


def test_wrappers_write_zero_findings_candidates_and_can_call() -> None:
    # Run every wrapper against its fixture into ONE shared graph, then assert the
    # graph holds only transport-tier facts: no Finding, no can_call, and no node
    # kind outside {host, service, endpoint}. Candidates are an Explorer runtime
    # type that never touches the graph, so "zero candidates" is proven structurally
    # by the wrappers importing no candidate/validator symbol (asserted below).
    graph, scope = _graph_and_scope()
    NmapRunner(graph=graph, scope=scope).ingest(_TARGET, _fixture("nmap-target.xml"))
    AmassRunner(graph=graph, scope=scope).ingest(_TARGET, _fixture("amass-target.txt"))
    SubfinderRunner(graph=graph, scope=scope).ingest(_TARGET, _fixture("subfinder-target.txt"))
    GobusterRunner(graph=graph, scope=scope).ingest(_TARGET, _fixture("gobuster-target.txt"))
    WhatWebRunner(graph=graph, scope=scope).ingest(_TARGET, _fixture("whatweb-target.json"))

    # Zero findings.
    assert graph.findings() == []
    # Zero can_call edges.
    assert graph.can_call_edges() == []
    # Only transport-tier node kinds exist.
    kinds = {attrs["kind"] for _, attrs in graph._g.nodes(data=True)}  # noqa: SLF001
    assert kinds <= {"host", "service", "endpoint"}
    # And we actually wrote facts (not a vacuous pass).
    assert graph.hosts()
    assert graph.services()


def test_recon_wrappers_import_no_validator_or_candidate_symbol() -> None:
    # Structural proof of "facts only" for the RECON (fact-emitter) tier: no recon
    # wrapper imports the Validator (run_oracle/write_finding) or the Explorer
    # candidate type. A recon wrapper has no code path to a confirmation OR a
    # candidate — it can only write graph facts.
    #
    # Scope is the fact-emitter modules only. The signal-gated (claim) tier —
    # base ``signal_gated.py`` + ``sqlmap``/``nuclei``/``nikto`` — legitimately
    # imports ``Candidate`` (it EMITS candidates by design, §9) and is covered by
    # its own AST guard in ``test_signal_gated_tools.py`` (which forbids the
    # validator / run_oracle / write_finding there). Mixing the two tiers into one
    # glob would wrongly forbid the candidate import the claim tier is built on.
    import ast

    import reachagent.recon.tools as pkg

    pkg_dir = Path(pkg.__file__).parent
    # The recon (fact) tier — explicitly enumerated so a new signal-gated module
    # can't silently fall under this fact-tier invariant, and a new recon module
    # must be added here on purpose.
    recon_tier_files = {"base.py", "nmap.py", "subdomains.py", "gobuster.py", "whatweb.py"}
    forbidden = (
        "reachagent.tools.validator",
        "reachagent.tools.candidate",
        "run_oracle",
        "write_finding",
    )
    offenders: list[str] = []
    for py in pkg_dir.glob("*.py"):
        if py.name not in recon_tier_files:
            continue
        tree = ast.parse(py.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module:
                if any(f in node.module for f in forbidden):
                    offenders.append(f"{py.name}: from {node.module}")
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if any(f in alias.name for f in forbidden):
                        offenders.append(f"{py.name}: import {alias.name}")
    assert offenders == []


# ---------------------------------------------------------------------------
# 6. Live path is env-gated and skipped by default
# ---------------------------------------------------------------------------


def test_live_run_is_skipped_when_not_env_gated(monkeypatch: pytest.MonkeyPatch) -> None:
    # Without REACHAGENT_RECON_LIVE, run() spawns nothing at all.
    import reachagent.recon.tools.base as base

    monkeypatch.setattr(
        base.subprocess,
        "run",
        lambda *_a, **_k: (_ for _ in ()).throw(AssertionError("must not spawn when not live")),
    )
    runner = NmapRunner(graph=ReachabilityGraph(), scope=_scope())

    result = runner.run(_TARGET, environ={})  # RECON_ENV_LIVE unset

    assert result.outcome is ReconOutcome.SKIPPED_NOT_LIVE


# ---------------------------------------------------------------------------
# Parse-robustness: a malformed fixture is audited as errored, never crashes
# ---------------------------------------------------------------------------


def test_malformed_nmap_xml_is_errored_not_crash() -> None:
    graph, scope = _graph_and_scope()
    runner = NmapRunner(graph=graph, scope=scope)
    result = runner.ingest(_TARGET, "<nmaprun><host><not-closed>")
    assert result.outcome is ReconOutcome.ERRORED
    assert graph.node_count() == 0
    assert runner.audit.entries[-1].outcome.startswith(ReconOutcome.ERRORED)


def test_scope_url_helper_coerces_bare_host() -> None:
    # A bare host / host:port / URL all reduce to a scope-checkable host.
    assert _scope_url("target.test").host == "target.test"
    assert _scope_url("target.test:8080").host == "target.test"
    assert _scope_url("https://target.test/path").host == "target.test"
