"""FastAPI GUI backend: a token-gated, cursor-resumable WebSocket + a minimal SPA shell.

The token model is a reference agent's own real, adopted design, stated
directly in its viewer docs (``docs/usage/viewer.mdx``, read in full):
"The token in the printed URL grants access to the run data... A request
without the token-derived session cannot read run data." That reference's
own token is on-by-default (always generated, always required) — the
correct default this module also uses. A different reference's own
``docs/api.md`` documents the opposite, real gap: its FastAPI backend's
bearer-style auth is "unprotected by default" whenever the relevant
credential env var happens to be unset, explicitly labeled "local dev
only." :func:`build_app` inverts that outright — a token is always
generated by the caller (:func:`generate_token`) and always required on
both the WebSocket and the steering endpoint; there is no unauthenticated
mode to fall into.

The steering endpoint is read-only by design, per CLAUDE.md's own stated
GUI principle (independently reconfirmed against this same reference's own
comparison of a permissive session model that has "no read-only-first
gating... any session's agent can presumably call any tool"): it can only
ever append a ``steering`` event that a human or agent may later read — it
has no code path to ``record_finding`` or any tool dispatch, and this
module holds no reference to a live agent's tool registry at all, so no
future change here can accidentally wire one in without a new, visible
import.

The WebSocket poll loop (rather than a true push/notify primitive) is a
deliberate simplification for a single local viewer, not an oversight —
:mod:`lalo.gui.events` is a plain synchronous class with no async
notification hook, and a live-scan dashboard has exactly one reader who
will not notice a sub-second delay. If this ever needs true low-latency
push, the upgrade path is an ``asyncio.Queue`` per connection that
``EventLog`` also notifies on ``append``/``update`` — not a rewrite of the
cursor protocol itself.

The same reference already cited above for its token model has directly
relevant content on a third concern this phase's own search hints raise:
client-side XSS from rendering untrusted content in the browser. Its own
frontend (``interface/viewer/frontend/src/components/live/tool-renderers/``
and ``vulnerability/``, confirmed via source, not just its comparison doc)
uses React's ``dangerouslySetInnerHTML`` in several places to inject
``highlight.js``-tokenized HTML for LLM-authored PoC scripts, code diffs,
and vulnerability descriptions — reasoned as low-risk there specifically
because ``highlight.js`` tokenizes its input as plain text rather than
parsing it as HTML, so target-controlled content flowing through never
executes as markup. :mod:`lalo.gui.static.app.js` (the companion frontend
this module serves) makes a stricter, simpler choice than that reasoning
requires: every dynamic value rendered into the page — agent status,
finding titles, chain node ids, event payload text, steering log lines, all
of it potentially target- or LLM-influenced — goes through ``textContent``,
never ``innerHTML`` and never any HTML-templating equivalent, so there is
no HTML-parsing step at all to reason about being safe. A plain DOM
console with no code-fence/PoC rendering has no legitimate use for
``innerHTML`` in the first place, so this is a narrower surface making a
narrower, more conservative choice — not a rejection of the reference's own
(correctly reasoned) approach to a harder problem it actually has and this
module does not.
"""

from __future__ import annotations

import asyncio
import json
import secrets
import threading
import uuid
from dataclasses import asdict
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Query, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from ..core.errors import AllProvidersFailedError
from ..core.logging import get_logger
from ..core.usage import DEFAULT_USAGE_PATH
from ..scan import ScanConfig, ScanRunner, load_run_events
from .events import EventLog

_log = get_logger("lalo.gui")

STATIC_DIR = Path(__file__).parent / "static"
_POLL_INTERVAL_S = 0.3
_DEFAULT_RUNS_DIR = Path.home() / ".lalo" / "runs"


class SteeringMessage(BaseModel):
    text: str


class ScanRequest(BaseModel):
    mission: str
    targets: list[str]
    exclude_targets: list[str] = []
    rules_of_engagement: str = ""


def generate_token() -> str:
    """A fresh, unguessable session token — always generated, never optional."""
    return secrets.token_urlsafe(32)


def _event_to_json(event: Any) -> dict[str, Any]:
    return asdict(event)


def _list_runs(runs_dir: Path) -> list[dict[str, Any]]:
    """Every run directory under ``runs_dir``, most recently modified first -
    pure filesystem enumeration, no separate run-index state to keep in sync.
    A directory missing/unreadable ``resume_manifest.json`` (a run that never
    got past the earliest preflight checks) still lists, just without a
    mission/targets summary.
    """
    if not runs_dir.exists():
        return []
    summaries: list[dict[str, Any]] = []
    for entry in runs_dir.iterdir():
        if not entry.is_dir():
            continue
        mission: str | None = None
        target_specs: list[str] = []
        try:
            manifest = json.loads((entry / "resume_manifest.json").read_text(encoding="utf-8"))
        except (OSError, ValueError):
            manifest = {}
        if isinstance(manifest, dict):
            raw_mission = manifest.get("mission")
            mission = raw_mission if isinstance(raw_mission, str) else None
            raw_targets = manifest.get("target_specs")
            target_specs = raw_targets if isinstance(raw_targets, list) else []
        summaries.append(
            {
                "run_id": entry.name,
                "mission": mission,
                "target_specs": target_specs,
                "has_report": (entry / "report.json").exists(),
                "modified_at": entry.stat().st_mtime,
            }
        )
    summaries.sort(key=lambda s: s["modified_at"], reverse=True)
    return summaries


def build_app(event_log: EventLog, token: str, *, runs_dir: Path | None = None) -> FastAPI:
    app = FastAPI()
    runs_dir = runs_dir or _DEFAULT_RUNS_DIR
    # A single mutable slot, not a list/registry: this GUI is a single-operator
    # local tool (CLAUDE.md's own design center) with one dashboard watching
    # one scan at a time, so "is a scan already running" is a plain None-check,
    # not a scheduler. /scan refuses a second launch while this is set.
    current_runner: dict[str, ScanRunner | None] = {"runner": None}

    def _authorized(candidate: str | None) -> bool:
        return candidate is not None and secrets.compare_digest(candidate, token)

    @app.get("/")
    def index() -> FileResponse:
        return FileResponse(STATIC_DIR / "index.html")

    @app.post("/scan")
    async def start_scan(
        request: ScanRequest,
        provided_token: str = Query(default="", alias="token"),
    ) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        mission = request.mission.strip()
        targets = [t.strip() for t in request.targets if t.strip()]
        exclude_targets = [t.strip() for t in request.exclude_targets if t.strip()]
        if not mission or not targets:
            return JSONResponse({"error": "'mission' and 'targets' are required"}, status_code=400)
        if current_runner["runner"] is not None:
            return JSONResponse({"error": "a scan is already running"}, status_code=409)

        run_dir = runs_dir / uuid.uuid4().hex[:12]
        config = ScanConfig(
            mission=mission,
            target_specs=targets,
            exclude_target_specs=exclude_targets,
            rules_of_engagement=request.rules_of_engagement.strip(),
            run_dir=run_dir,
            usage_path=DEFAULT_USAGE_PATH,
        )
        runner = ScanRunner(config, event_log=event_log)
        current_runner["runner"] = runner

        def _run_and_clear() -> None:
            try:
                runner.run()
            except Exception as exc:  # noqa: BLE001 - a background thread's own
                # exception has no caller to propagate to; the dashboard is the
                # only place this failure can surface, so it must be a status
                # event, never a silently dead thread.
                _log.exception("scan failed")
                payload: dict[str, object] = {"event": "scan_failed", "error": str(exc)}
                # AllProvidersFailedError already carries its per-provider
                # detail as real attributes (see core/errors.py) - str(exc)
                # alone flattens them into one line the frontend can't
                # re-segment, so surface role/failures as their own fields
                # too for a structured, per-provider rendering in the GUI.
                if isinstance(exc, AllProvidersFailedError):
                    payload["role"] = exc.role
                    payload["failures"] = [
                        {"provider": name, "reason": reason} for name, reason in exc.failures
                    ]
                event_log.append("status", payload)
            finally:
                current_runner["runner"] = None

        threading.Thread(target=_run_and_clear, daemon=True).start()
        return JSONResponse({"ok": True, "run_dir": str(run_dir)})

    @app.get("/status")
    def status(provided_token: str = Query(default="", alias="token")) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        cursor, events = event_log.snapshot()
        findings_count = sum(1 for e in events if e.category == "finding")
        last_status = next((e.payload for e in reversed(events) if e.category == "status"), None)
        return JSONResponse(
            {
                "running": current_runner["runner"] is not None,
                "cursor": cursor,
                "findings_count": findings_count,
                "last_status": last_status,
            }
        )

    @app.get("/runs")
    def list_runs(provided_token: str = Query(default="", alias="token")) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        return JSONResponse({"runs": _list_runs(runs_dir)})

    @app.get("/runs/{run_id}/events")
    def run_events(
        run_id: str, provided_token: str = Query(default="", alias="token")
    ) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        # Starlette's default path converter already excludes "/" from a
        # single {run_id} segment; this additionally rejects the one
        # traversal shape still expressible as one segment.
        if not run_id or run_id in (".", ".."):
            return JSONResponse({"error": "invalid run_id"}, status_code=400)
        run_path = runs_dir / run_id
        if not run_path.is_dir():
            return JSONResponse({"error": "run not found"}, status_code=404)
        replay = load_run_events(run_path)
        cursor, events = replay.snapshot()
        return JSONResponse({"cursor": cursor, "events": [_event_to_json(e) for e in events]})

    @app.post("/scan/stop")
    async def stop_scan(provided_token: str = Query(default="", alias="token")) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        runner = current_runner["runner"]
        if runner is None:
            return JSONResponse({"error": "no scan is running"}, status_code=400)
        runner.cancel()
        return JSONResponse({"ok": True})

    @app.post("/steer")
    async def steer(
        message: SteeringMessage,
        provided_token: str = Query(default="", alias="token"),
    ) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        text = message.text.strip()
        if not text:
            return JSONResponse({"error": "'text' is required"}, status_code=400)
        event_log.append("steering", {"text": text})
        return JSONResponse({"ok": True})

    @app.websocket("/ws")
    async def ws(
        websocket: WebSocket,
        provided_token: str = Query(default="", alias="token"),
        cursor: int | None = Query(default=None),
    ) -> None:
        if not _authorized(provided_token):
            await websocket.close(code=4401, reason="invalid token")
            return
        await websocket.accept()
        try:
            current, events = (
                event_log.changes_since(cursor) if cursor is not None else event_log.snapshot()
            )
        except ValueError as exc:
            await websocket.close(code=4400, reason=str(exc))
            return

        await websocket.send_json(
            {"cursor": current, "events": [_event_to_json(e) for e in events]}
        )
        last_cursor = current
        try:
            while True:
                await asyncio.sleep(_POLL_INTERVAL_S)
                new_cursor, changed = event_log.changes_since(last_cursor)
                if changed:
                    await websocket.send_json(
                        {"cursor": new_cursor, "events": [_event_to_json(e) for e in changed]}
                    )
                last_cursor = new_cursor
        except WebSocketDisconnect:
            return

    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
    return app


def main() -> None:
    """Entry point for the ``lalo-gui`` script: the GUI is the primary way to run L4L0.

    ``POST /scan`` (mission + target specs, token-gated, one scan at a time)
    launches a real :class:`~lalo.scan.ScanRunner` on a background thread,
    which streams every event into the returned ``EventLog`` — the wiring
    this function's docstring used to describe as a future integration
    pass's job now lives in :mod:`lalo.scan`, called from here.
    """
    import uvicorn

    event_log = EventLog()
    token = generate_token()
    app = build_app(event_log, token)
    host, port = "127.0.0.1", 8765
    print(f"L4L0 GUI: http://{host}:{port}/?token={token}")
    uvicorn.run(app, host=host, port=port)
