"""FastAPI GUI backend: a token-gated, cursor-resumable WebSocket + a minimal SPA shell.

The token model is a reference agent's own real, adopted design, stated
directly in its viewer docs (``docs/usage/viewer.mdx``, read in full):
"The token in the printed URL grants access to the run data... A request
without the token-derived session cannot read run data." That reference's
own token is on-by-default (always generated, always required) — the
correct default this module also uses. A different reference's own
``docs/api.md`` documents the opposite, real gap: its FastAPI backend's
bearer-style auth is "unprotected by default" whenever the relevant
credential env var happens to be unset, explicitly labeled "local dev
only." :func:`build_app` inverts that outright — a token is always
generated by the caller (:func:`generate_token`) and always required on
both the WebSocket and the steering endpoint; there is no unauthenticated
mode to fall into.

The steering endpoint is read-only by design, per CLAUDE.md's own stated
GUI principle (independently reconfirmed against this same reference's own
comparison of a permissive session model that has "no read-only-first
gating... any session's agent can presumably call any tool"): it can only
ever append a ``steering`` event that a human or agent may later read — it
has no code path to ``record_finding`` or any tool dispatch, and this
module holds no reference to a live agent's tool registry at all, so no
future change here can accidentally wire one in without a new, visible
import.

The WebSocket poll loop (rather than a true push/notify primitive) is a
deliberate simplification for a single local viewer, not an oversight —
:mod:`lalo.gui.events` is a plain synchronous class with no async
notification hook, and a live-scan dashboard has exactly one reader who
will not notice a sub-second delay. If this ever needs true low-latency
push, the upgrade path is an ``asyncio.Queue`` per connection that
``EventLog`` also notifies on ``append``/``update`` — not a rewrite of the
cursor protocol itself.

The same reference already cited above for its token model has directly
relevant content on a third concern this phase's own search hints raise:
client-side XSS from rendering untrusted content in the browser. Its own
frontend (``interface/viewer/frontend/src/components/live/tool-renderers/``
and ``vulnerability/``, confirmed via source, not just its comparison doc)
uses React's ``dangerouslySetInnerHTML`` in several places to inject
``highlight.js``-tokenized HTML for LLM-authored PoC scripts, code diffs,
and vulnerability descriptions — reasoned as low-risk there specifically
because ``highlight.js`` tokenizes its input as plain text rather than
parsing it as HTML, so target-controlled content flowing through never
executes as markup. :mod:`lalo.gui.static.app.js` (the companion frontend
this module serves) makes a stricter, simpler choice than that reasoning
requires: every dynamic value rendered into the page — agent status,
finding titles, chain node ids, event payload text, steering log lines, all
of it potentially target- or LLM-influenced — goes through ``textContent``,
never ``innerHTML`` and never any HTML-templating equivalent, so there is
no HTML-parsing step at all to reason about being safe. A plain DOM
console with no code-fence/PoC rendering has no legitimate use for
``innerHTML`` in the first place, so this is a narrower surface making a
narrower, more conservative choice — not a rejection of the reference's own
(correctly reasoned) approach to a harder problem it actually has and this
module does not.
"""

from __future__ import annotations

import asyncio
import secrets
from dataclasses import asdict
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Query, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from .events import EventLog

STATIC_DIR = Path(__file__).parent / "static"
_POLL_INTERVAL_S = 0.3


class SteeringMessage(BaseModel):
    text: str


def generate_token() -> str:
    """A fresh, unguessable session token — always generated, never optional."""
    return secrets.token_urlsafe(32)


def _event_to_json(event: Any) -> dict[str, Any]:
    return asdict(event)


def build_app(event_log: EventLog, token: str) -> FastAPI:
    app = FastAPI()

    def _authorized(candidate: str | None) -> bool:
        return candidate is not None and secrets.compare_digest(candidate, token)

    @app.get("/")
    def index() -> FileResponse:
        return FileResponse(STATIC_DIR / "index.html")

    @app.post("/steer")
    async def steer(
        message: SteeringMessage,
        provided_token: str = Query(default="", alias="token"),
    ) -> JSONResponse:
        if not _authorized(provided_token):
            return JSONResponse({"error": "invalid token"}, status_code=403)
        text = message.text.strip()
        if not text:
            return JSONResponse({"error": "'text' is required"}, status_code=400)
        event_log.append("steering", {"text": text})
        return JSONResponse({"ok": True})

    @app.websocket("/ws")
    async def ws(
        websocket: WebSocket,
        provided_token: str = Query(default="", alias="token"),
        cursor: int | None = Query(default=None),
    ) -> None:
        if not _authorized(provided_token):
            await websocket.close(code=4401, reason="invalid token")
            return
        await websocket.accept()
        try:
            current, events = (
                event_log.changes_since(cursor) if cursor is not None else event_log.snapshot()
            )
        except ValueError as exc:
            await websocket.close(code=4400, reason=str(exc))
            return

        await websocket.send_json(
            {"cursor": current, "events": [_event_to_json(e) for e in events]}
        )
        last_cursor = current
        try:
            while True:
                await asyncio.sleep(_POLL_INTERVAL_S)
                new_cursor, changed = event_log.changes_since(last_cursor)
                if changed:
                    await websocket.send_json(
                        {"cursor": new_cursor, "events": [_event_to_json(e) for e in changed]}
                    )
                last_cursor = new_cursor
        except WebSocketDisconnect:
            return

    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
    return app


def main() -> None:
    """Entry point for the ``lalo-gui`` script: the GUI is the primary way to run L4L0.

    Wiring a live scan's events into the returned ``EventLog`` (via a
    running :class:`~lalo.agent.loop.AgentLoop`'s own ``on_event`` callback)
    is deliberately out of scope here — that spans nearly every phase built
    so far (provider/config resolution, the runtime container, the full
    tool registry, prompts) and belongs to whichever future integration
    pass assembles them into one runnable scan, not to the GUI backend
    module itself. This entry point serves the live-viewing mechanism ready
    for that wiring: anything that calls ``event_log.append``/``.update``
    appears in the dashboard immediately, reconnect-safe.
    """
    import uvicorn

    event_log = EventLog()
    token = generate_token()
    app = build_app(event_log, token)
    host, port = "127.0.0.1", 8765
    print(f"L4L0 GUI: http://{host}:{port}/?token={token}")
    uvicorn.run(app, host=host, port=port)
